### ISSUE TITLE
Match error when setting include_erts and include_system_libs to paths

### ISSUE THREAD

**Issue by mariosangiorgio** [bitwalker/distillery#108]
Hello,

I have a configuration I'd like to use to package an application with the version of `erts` and of the libraries needed by my Raspberry Pi. It looks like the following:

```
environment :raspberry_pi do
  set include_erts: "../erlang_rpi/erts-8.0.1/"
  set include_system_libs: "../erlang_rpi/"
  set include_src: false
end

release :price_watch do
  set version: current_version(:price_watch)
end
```

`erlang_rpi` contains a copy of the libraries I grabbed from the Raspberry Pi installation.

When I try to run it, I get a match error. It looks like setting strings for `include_erts` and `include_system_libs` is triggering a code path that needs apps to be set.

```
** (MatchError) no match of right hand side value: []                                                      
    (distillery) lib/mix/lib/releases/utils.ex:232: anonymous fn/2 in Mix.Releases.Utils.get_apps/1        
    (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2                                              
    (distillery) lib/mix/lib/releases/utils.ex:228: Mix.Releases.Utils.get_apps/1                          
    (distillery) lib/mix/lib/releases/assembler.ex:79: Mix.Releases.Assembler.apply_configuration/2        
    (distillery) lib/mix/lib/releases/assembler.ex:27: Mix.Releases.Assembler.assemble/1                   
    (distillery) lib/distillery/tasks/release.ex:108: Mix.Tasks.Release.run/1                              
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3                                                         
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

Can you please help me figuring out if I'm doing something wrong or if I found a bug?

Thanks,
Mario

**Comment by bitwalker** [comment]
It's likely a bug, I'll take a look ASAP

**Comment by mariosangiorgio** [comment]
I tracked the issue down to something here
`[corrected_app_path] = Path.wildcard(Path.join(lib_dir, "#{a}-*"))`

```

    # Correct any ERTS libs which should be pulled from the correct
    # ERTS directory, not from the current environment.
    apps = case release.profile.include_erts do
             true  -> apps
             false -> apps
             p when is_binary(p) ->
               lib_dir = Path.expand(Path.join(p, "lib"))
               Enum.map(apps, fn %App{name: a} = app ->
                 case is_erts_lib?(app.path) do
                   false -> app
                   true ->
                     [corrected_app_path] = Path.wildcard(Path.join(lib_dir, "#{a}-*"))
                     [_, corrected_app_vsn] = String.split(Path.basename(corrected_app_path), "-", trim: true)
                     %{app | :vsn => corrected_app_vsn,
                             :path => corrected_app_path}
                 end
               end)
           end
```

This is the content of the folders
```
$ ls ../erlang_rpi/
erts-8.0.1 lib
$ ls ../erlang_rpi/erts-8.0.1                                                                                                      
bin     doc     include lib     man     src
$ ls ../erlang_rpi/erts-8.0.1/lib
internal    liberts.a   liberts_r.a
$ ls ../erlang_rpi/lib
asn1-4.0.3
crypto-3.7
gettext-0.11.0
...
```

It looks it's looking into `../erlang_rpi/erts-8.0.1/lib`, which doesn't have anything matching the pattern. Does the folder contain the expected content? I might have done something wrong getting the libraries.

**Comment by bitwalker** [comment]
You're right, that does appear to be the problem. I've pushed a fix to master, could you give it a shot?

**Comment by mariosangiorgio** [comment]
I'm still having issues. I think that the root cause of the problem is that different parts of the code expect `include_erts` to be set to different things. Some expect it to be set to  `"../erlang_rpi/erts-8.0.1/"` while other wants it to be `"../erlang_rpi"`.

Can you confirm with me what is the expected path in this case? I am assuming the first is correct and I am going to make my local master agree with that assumption. If I manage to get something working I'll submit a pull request.
