### ISSUE TITLE
No application config provided in Pre-start Hook in 2.0-pre

### ISSUE THREAD

**Issue by erikreedstrom** [bitwalker/distillery#477]
Patched around the `:ok = Application.load(:core_api)`, but noticed no migrations were running.
Added `Logger.info(inspect(Application.get_all_env(:core_api)))` and found that there is no config being returned for the app; return is empty list `[]`.

I have verified the config is being compiled as `sys.confg` has the values in the release:

```
 {core_api,
     [{ecto_repos,['Elixir.CoreAPI.Repo']},
```

### Steps to reproduce

1. Add migrate command following the guide https://hexdocs.pm/distillery/2.0.0-rc.8/running_migrations.html#content
2. MIX_ENV=prod mix release --env=prod
3. env $(cat .env.prod | xargs) _build/prod/rel/core_api/bin/core_api foreground

<summary>
  <details>

```
==> Loading configuration..
==> Assembling release..
==> Building release core_api:0.0.0+version using environment prod
==> Discovered applications:
  > kernel-6.0
  |
  |  from: /Users/erikreedstrom/.asdf/installs/erlang/21.0.4/lib/kernel-6.0
  |  applications: none
  |  includes: none
  |_____

  > stdlib-3.5.1
  |
  |  from: /Users/erikreedstrom/.asdf/installs/erlang/21.0.4/lib/stdlib-3.5.1
  |  applications:
  |      :kernel
  |  includes: none
  |_____

  > compiler-7.2.2
  |
  |  from: /Users/erikreedstrom/.asdf/installs/erlang/21.0.4/lib/compiler-7.2.2
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > elixir-1.7.2
  |
  |  from: /Users/erikreedstrom/.asdf/installs/elixir/1.7.2/bin/../lib/elixir
  |  applications:
  |      :kernel
  |      :stdlib
  |      :compiler
  |  includes: none
  |_____

  > iex-1.7.2
  |
  |  from: /Users/erikreedstrom/.asdf/installs/elixir/1.7.2/bin/../lib/iex
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > mix-1.7.2
  |
  |  from: /Users/erikreedstrom/.asdf/installs/elixir/1.7.2/bin/../lib/mix
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > sasl-3.2
  |
  |  from: /Users/erikreedstrom/.asdf/installs/erlang/21.0.4/lib/sasl-3.2
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > runtime_tools-1.13
  |
  |  from: /Users/erikreedstrom/.asdf/installs/erlang/21.0.4/lib/runtime_tools-1.13
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > logger-1.7.2
  |
  |  from: /Users/erikreedstrom/.asdf/installs/elixir/1.7.2/bin/../lib/logger
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > artificery-0.2.6
  |
  |  from: _build/prod/lib/artificery
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > distillery-2.0.0-rc.8
  |
  |  from: _build/prod/lib/distillery
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :runtime_tools
  |      :logger
  |      :artificery
  |  includes: none
  |_____

  > p1_utils-1.0.10
  |
  |  from: _build/prod/lib/p1_utils
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > inets-7.0
  |
  |  from: /Users/erikreedstrom/.asdf/installs/erlang/21.0.4/lib/inets-7.0
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > jason-1.1.1
  |
  |  from: _build/prod/lib/jason
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > crypto-4.3
  |
  |  from: /Users/erikreedstrom/.asdf/installs/erlang/21.0.4/lib/crypto-4.3
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > asn1-5.0.6
  |
  |  from: /Users/erikreedstrom/.asdf/installs/erlang/21.0.4/lib/asn1-5.0.6
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > public_key-1.6.1
  |
  |  from: /Users/erikreedstrom/.asdf/installs/erlang/21.0.4/lib/public_key-1.6.1
  |  applications:
  |      :asn1
  |      :crypto
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > ssl-9.0
  |
  |  from: /Users/erikreedstrom/.asdf/installs/erlang/21.0.4/lib/ssl-9.0
  |  applications:
  |      :crypto
  |      :public_key
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > libcluster-3.0.2
  |
  |  from: _build/prod/lib/libcluster
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :inets
  |      :jason
  |      :crypto
  |      :ssl
  |  includes: none
  |_____

  > gen_state_machine-2.0.2
  |
  |  from: _build/prod/lib/gen_state_machine
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > libring-1.3.1
  |
  |  from: _build/prod/lib/libring
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :crypto
  |  includes: none
  |_____

  > swarm-3.3.1
  |
  |  from: _build/prod/lib/swarm
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :crypto
  |      :gen_state_machine
  |      :libring
  |  includes: none
  |_____

  > elixir_uuid-1.2.0
  |
  |  from: _build/prod/lib/elixir_uuid
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > format-0.1.0
  |
  |  from: _build/prod/lib/format
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > elixlsx-0.4.0
  |
  |  from: _build/prod/lib/elixlsx
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > inflex-1.10.0
  |
  |  from: _build/prod/lib/inflex
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > gettext-0.15.0
  |
  |  from: _build/prod/lib/gettext
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > sage-0.4.0
  |
  |  from: _build/prod/lib/sage
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > decimal-1.5.0
  |
  |  from: _build/prod/lib/decimal
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > absinthe-1.4.13
  |
  |  from: _build/prod/lib/absinthe
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > elixir_make-0.4.2
  |
  |  from: _build/prod/lib/elixir_make
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > bcrypt_elixir-1.0.9
  |
  |  from: _build/prod/lib/bcrypt_elixir
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :crypto
  |      :elixir_make
  |  includes: none
  |_____

  > comeonin-4.1.1
  |
  |  from: _build/prod/lib/comeonin
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > gen_stage-0.14.0
  |
  |  from: _build/prod/lib/gen_stage
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > flow-0.14.2
  |
  |  from: _build/prod/lib/flow
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :gen_stage
  |  includes: none
  |_____

  > unicode_util_compat-0.3.1
  |
  |  from: _build/prod/lib/unicode_util_compat
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > idna-5.1.2
  |
  |  from: _build/prod/lib/idna
  |  applications:
  |      :kernel
  |      :stdlib
  |      :unicode_util_compat
  |  includes: none
  |_____

  > mimerl-1.0.2
  |
  |  from: _build/prod/lib/mimerl
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > certifi-2.3.1
  |
  |  from: _build/prod/lib/certifi
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > ssl_verify_fun-1.1.1
  |
  |  from: _build/prod/lib/ssl_verify_fun
  |  applications:
  |      :kernel
  |      :stdlib
  |      :ssl
  |  includes: none
  |_____

  > metrics-1.0.1
  |
  |  from: _build/prod/lib/metrics
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > hackney-1.13.0
  |
  |  from: _build/prod/lib/hackney
  |  applications:
  |      :kernel
  |      :stdlib
  |      :crypto
  |      :asn1
  |      :public_key
  |      :ssl
  |      :idna
  |      :mimerl
  |      :certifi
  |      :ssl_verify_fun
  |      :metrics
  |  includes: none
  |_____

  > tzdata-0.5.17
  |
  |  from: _build/prod/lib/tzdata
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :hackney
  |      :logger
  |  includes: none
  |_____

  > combine-0.10.0
  |
  |  from: _build/prod/lib/combine
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > timex-3.2.2
  |
  |  from: _build/prod/lib/timex
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :tzdata
  |      :gettext
  |      :combine
  |  includes: none
  |_____

  > httpoison-1.2.0
  |
  |  from: _build/prod/lib/httpoison
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :hackney
  |  includes: none
  |_____

  > poison-3.1.0
  |
  |  from: _build/prod/lib/poison
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > cloudex-1.1.3
  |
  |  from: _build/prod/lib/cloudex
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :poison
  |      :tzdata
  |      :timex
  |      :httpoison
  |  includes: none
  |_____

  > phoenix_pubsub-1.0.2
  |
  |  from: _build/prod/lib/phoenix_pubsub
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :crypto
  |  includes: none
  |_____

  > ranch-1.3.2
  |
  |  from: _build/prod/lib/ranch
  |  applications:
  |      :kernel
  |      :stdlib
  |      :ssl
  |  includes: none
  |_____

  > cowlib-1.0.2
  |
  |  from: _build/prod/lib/cowlib
  |  applications:
  |      :kernel
  |      :stdlib
  |      :crypto
  |  includes: none
  |_____

  > cowboy-1.1.2
  |
  |  from: _build/prod/lib/cowboy
  |  applications:
  |      :kernel
  |      :stdlib
  |      :ranch
  |      :cowlib
  |      :crypto
  |  includes: none
  |_____

  > xmerl-1.3.17
  |
  |  from: /Users/erikreedstrom/.asdf/installs/erlang/21.0.4/lib/xmerl-1.3.17
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > syntax_tools-2.1.5
  |
  |  from: /Users/erikreedstrom/.asdf/installs/erlang/21.0.4/lib/syntax_tools-2.1.5
  |  applications:
  |      :stdlib
  |  includes: none
  |_____

  > recon-2.3.2
  |
  |  from: _build/prod/lib/recon
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > rabbit_common-3.6.16
  |
  |  from: _build/prod/lib/rabbit_common
  |  applications:
  |      :kernel
  |      :stdlib
  |      :compiler
  |      :syntax_tools
  |      :xmerl
  |      :recon
  |  includes: none
  |_____

  > amqp_client-3.6.16
  |
  |  from: _build/prod/lib/amqp_client
  |  applications:
  |      :kernel
  |      :stdlib
  |      :xmerl
  |      :rabbit_common
  |  includes: none
  |_____

  > amqp-0.3.1
  |
  |  from: _build/prod/lib/amqp
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :amqp_client
  |  includes: none
  |_____

  > ulid-1.0.0
  |
  |  from: _build/prod/lib/ulid
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > mime-1.3.0
  |
  |  from: _build/prod/lib/mime
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > plug-1.6.1
  |
  |  from: _build/prod/lib/plug
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :crypto
  |      :logger
  |      :mime
  |  includes: none
  |_____

  > absinthe_plug-1.4.5
  |
  |  from: _build/prod/lib/absinthe_plug
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :plug
  |      :absinthe
  |  includes: none
  |_____

  > bodyguard-2.2.2
  |
  |  from: _build/prod/lib/bodyguard
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :plug
  |  includes: none
  |_____

  > cors_plug-1.5.2
  |
  |  from: _build/prod/lib/cors_plug
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > plug_attack-0.4.0
  |
  |  from: _build/prod/lib/plug_attack
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > inet_cidr-1.0.3
  |
  |  from: _build/prod/lib/inet_cidr
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > remote_ip-0.1.4
  |
  |  from: _build/prod/lib/remote_ip
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :plug
  |  includes:
  |      :combine
  |  :inet_cidr  |_____

  > eex-1.7.2
  |
  |  from: /Users/erikreedstrom/.asdf/installs/elixir/1.7.2/bin/../lib/eex
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > phoenix-1.3.3
  |
  |  from: _build/prod/lib/phoenix
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :plug
  |      :poison
  |      :logger
  |      :eex
  |      :phoenix_pubsub
  |      :crypto
  |  includes: none
  |_____

  > base64url-0.0.1
  |
  |  from: _build/prod/lib/base64url
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > jose-1.8.4
  |
  |  from: _build/prod/lib/jose
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :crypto
  |      :asn1
  |      :public_key
  |      :base64url
  |  includes: none
  |_____

  > guardian-1.1.0
  |
  |  from: _build/prod/lib/guardian
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :crypto
  |      :logger
  |      :jose
  |      :poison
  |  includes: none
  |_____

  > sentry-6.4.1
  |
  |  from: _build/prod/lib/sentry
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :hackney
  |      :poison
  |      :logger
  |  includes: none
  |_____

  > abnf2-0.1.4
  |
  |  from: _build/prod/lib/abnf2
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > ex_cldr-1.6.4
  |
  |  from: _build/prod/lib/ex_cldr
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :abnf2
  |      :decimal
  |  includes: none
  |_____

  > ex_cldr_currencies-1.0.0
  |
  |  from: _build/prod/lib/ex_cldr_currencies
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :ex_cldr
  |  includes: none
  |_____

  > ex_cldr_numbers-1.5.1
  |
  |  from: _build/prod/lib/ex_cldr_numbers
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :decimal
  |      :ex_cldr
  |      :ex_cldr_currencies
  |  includes: none
  |_____

  > ex_cldr_lists-1.1.0
  |
  |  from: _build/prod/lib/ex_cldr_lists
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :jason
  |      :ex_cldr
  |      :ex_cldr_numbers
  |  includes: none
  |_____

  > connection-1.0.4
  |
  |  from: _build/prod/lib/connection
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > db_connection-1.1.3
  |
  |  from: _build/prod/lib/db_connection
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :connection
  |  includes: none
  |_____

  > postgrex-0.13.5
  |
  |  from: _build/prod/lib/postgrex
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :db_connection
  |      :decimal
  |      :crypto
  |  includes: none
  |_____

  > poolboy-1.5.1
  |
  |  from: _build/prod/lib/poolboy
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > ecto-2.2.10
  |
  |  from: _build/prod/lib/ecto
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :decimal
  |      :poolboy
  |      :crypto
  |  includes: none
  |_____

  > absinthe_ecto-0.1.3
  |
  |  from: _build/prod/lib/absinthe_ecto
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :absinthe
  |      :ecto
  |  includes: none
  |_____

  > absinthe_relay-1.4.3
  |
  |  from: _build/prod/lib/absinthe_relay
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :absinthe
  |  includes: none
  |_____

  > decoratex-1.1.0
  |
  |  from: _build/prod/lib/decoratex
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > msgpax-2.1.1
  |
  |  from: _build/prod/lib/msgpax
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > timber-2.8.2
  |
  |  from: _build/prod/lib/timber
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :poison
  |      :msgpax
  |      :hackney
  |  includes: none
  |_____

  > crontab-1.1.3
  |
  |  from: _build/prod/lib/crontab
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > quantum-2.2.7
  |
  |  from: _build/prod/lib/quantum
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :gen_stage
  |      :crontab
  |  includes: none
  |_____

  > ecto_enum-1.1.0
  |
  |  from: _build/prod/lib/ecto_enum
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :ecto
  |  includes: none
  |_____

  > task_bunny-0.3.3
  |
  |  from: _build/prod/lib/task_bunny
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :poison
  |      :amqp
  |  includes: none
  |_____

  > task_bunny_sentry-0.1.3
  |
  |  from: _build/prod/lib/task_bunny_sentry
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :sentry
  |      :task_bunny
  |  includes: none
  |_____

  > fast_yaml-1.0.11
  |
  |  from: _build/prod/lib/fast_yaml
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > approximate_histogram-0.1.1
  |
  |  from: _build/prod/lib/approximate_histogram
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > scout_apm-0.4.6
  |
  |  from: _build/prod/lib/scout_apm
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :hackney
  |      :plug
  |      :poison
  |      :approximate_histogram
  |  includes: none
  |_____

  > boltun-1.0.2
  |
  |  from: _build/prod/lib/boltun
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :postgrex
  |      :logger
  |  includes: none
  |_____

  > geo-3.0.0
  |
  |  from: _build/prod/lib/geo
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > geo_postgis-2.0.0
  |
  |  from: _build/prod/lib/geo_postgis
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :postgrex
  |      :geo
  |  includes: none
  |_____

  > phoenix_ecto-3.3.0
  |
  |  from: _build/prod/lib/phoenix_ecto
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :ecto
  |      :plug
  |  includes: none
  |_____

  > core_api-0.0.0+version
  |
  |  from: _build/prod/lib/core_api
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :runtime_tools
  |      :p1_utils
  |      :libcluster
  |      :swarm
  |      :elixir_uuid
  |      :format
  |      :elixlsx
  |      :inflex
  |      :gettext
  |      :sage
  |      :decimal
  |      :absinthe
  |      :jason
  |      :bcrypt_elixir
  |      :comeonin
  |      :flow
  |      :timex
  |      :httpoison
  |      :cloudex
  |      :phoenix_pubsub
  |      :cowboy
  |      :amqp
  |      :ulid
  |      :absinthe_plug
  |      :bodyguard
  |      :cors_plug
  |      :plug_attack
  |      :remote_ip
  |      :phoenix
  |      :guardian
  |      :sentry
  |      :ex_cldr_lists
  |      :postgrex
  |      :ecto
  |      :absinthe_ecto
  |      :absinthe_relay
  |      :decoratex
  |      :timber
  |      :quantum
  |      :ecto_enum
  |      :task_bunny
  |      :task_bunny_sentry
  |      :fast_yaml
  |      :scout_apm
  |      :boltun
  |      :geo_postgis
  |      :phoenix_ecto
  |  includes: none
  |_____

==> Running validation checks..
    > Mix.Releases.Checks.Erts * PASS
    > Mix.Releases.Checks.Cookie * PASS
    > Mix.Releases.Checks.MissingApps * WARN

One or more direct or transitive dependencies are missing from
    :applications or :included_applications, they will not be included
    in the release:

        :ex_machina
        :parse_trans

    This can cause your application to fail at runtime. If you are sure
    that this is not an issue, you may ignore this warning.

==> Generated overlay vars:
    release_name=:core_api
    release_version="0.0.0+version"
    is_upgrade=false
    upgrade_from=:latest
    dev_mode=false
    include_erts=true
    include_src=false
    include_system_libs=true
    erl_opts=""
    run_erl_env=""
    erts_vsn="10.0.4"
    output_dir="_build/prod/rel/core_api"
==> Copying applications to _build/prod/rel/core_api
==> Generating start_erl.data
==> Generating vm.args from rel/vm.args
==> Generating sys.config from config/config.exs
==> Including ERTS 10.0.4 from /Users/erikreedstrom/.asdf/installs/erlang/21.0.4/erts-10.0.4
==> Generating boot script
==> Generating RELEASES
==> Generating start_clean.boot
==> Generating no_dot_erlang.boot
==> Applying overlays
==> Applying mkdir overlay
    dst: releases/0.0.0+version/hooks
==> Applying mkdir overlay
    dst: releases/0.0.0+version/hooks/pre_configure.d
==> Applying mkdir overlay
    dst: releases/0.0.0+version/hooks/post_configure.d
==> Applying mkdir overlay
    dst: releases/0.0.0+version/hooks/pre_start.d
==> Applying mkdir overlay
    dst: releases/0.0.0+version/hooks/post_start.d
==> Applying mkdir overlay
    dst: releases/0.0.0+version/hooks/pre_stop.d
==> Applying mkdir overlay
    dst: releases/0.0.0+version/hooks/post_stop.d
==> Applying mkdir overlay
    dst: releases/0.0.0+version/hooks/pre_upgrade.d
==> Applying mkdir overlay
    dst: releases/0.0.0+version/hooks/post_upgrade.d
==> Applying copy overlay
    src: rel/hooks/pre_start
    dst: releases/0.0.0+version/hooks/pre_start.d
==> Applying copy overlay
    src: _build/prod/lib/distillery/priv/libexec
    dst: releases/0.0.0+version/libexec
==> Applying mkdir overlay
    dst: releases/0.0.0+version/commands
==> Packaging release..
==> Archiving core_api-0.0.0+version
==> Writing archive to /Users/erikreedstrom/Projects/homepolish/core_api/_build/prod/rel/core_api/releases/0.0.0+version/core_api.tar.gz
==> Updating archive..
==> Including system libs from current Erlang installation
==> Saving archive..
==> Archive saved!
Release succesfully built!
To start the release you have built, you can use one of the following tasks:

    # start a shell, like 'iex -S mix'
    > _build/prod/rel/core_api/bin/core_api console

    # start in the foreground, like 'mix run --no-halt'
    > _build/prod/rel/core_api/bin/core_api foreground

    # start in the background, must be stopped with the 'stop' command
    > _build/prod/rel/core_api/bin/core_api start

If you started a release elsewhere, and wish to connect to it:

    # connects a local shell to the running node
    > _build/prod/rel/core_api/bin/core_api remote_console

    # connects directly to the running node's console
    > _build/prod/rel/core_api/bin/core_api attach

For a complete listing of commands and their use:

    > _build/prod/rel/core_api/bin/core_api help
```

  </details>
</summary>

### Description of issue

- What are the expected results?

Application configuration is returned when calling `Application.get_all_env(:core_api)`

- What version of Distillery?

2.0-rc8

- What OS, Erlang/Elixir versions are you seeing this issue on?

OS X 10.13.6, 21.0.4/1.7.2

- If possible, also provide your `rel/config.exs`, as it is often
  my first troubleshooting question, and you'll save us both time :)

<summary>
  <details>

```
# Import all plugins from `rel/plugins`
# They can then be used by adding `plugin MyPlugin` to
# either an environment, or release definition, where
# `MyPlugin` is the name of the plugin module.
Path.join(["rel", "plugins", "*.exs"])
|> Path.wildcard()
|> Enum.map(&Code.eval_file(&1))

use Mix.Releases.Config,
  # This sets the default release built by `mix release`
  default_release: :default,
  # This sets the default environment used by `mix release`
  default_environment: Mix.env()

# For a full list of config options for both releases
# and environments, visit https://hexdocs.pm/distillery/configuration.html

# You may define one or more environments in this file,
# an environment's settings will override those of a release
# when building in that environment, this combination of release
# and environment configuration is called a profile

environment :dev do
  # If you are running Phoenix, you should make sure that
  # server: true is set and the code reloader is disabled,
  # even in dev mode.
  # It is recommended that you build with MIX_ENV=prod and pass
  # the --env flag to Distillery explicitly if you want to use
  # dev mode.
  set(dev_mode: true)
  set(include_erts: false)
  set(cookie: :"IJeobJ3Y>|3Q~P|L~$F&YuV)`f!8$EaZOnpN[Z(UOstDk/qEz6BSBAnKo&E&l(!3")
end

environment :prod do
  set(include_erts: true)
  set(include_src: false)
  # this is just to get rid of the warning. see https://github.com/bitwalker/distillery/issues/140
  set(cookie: :"${MY_COOKIE}")
  set(vm_args: "rel/vm.args")
  set(pre_start_hooks: "rel/hooks/pre_start")
end

# You may define one or more releases in this file.
# If you have not set a default release, or selected one
# when running `mix release`, the first release in the file
# will be used by default

release :core_api do
  set(version: current_version(:core_api))

  set(
    applications: [
      :runtime_tools
    ]
  )
end
```

  </details>
</summary>

**Comment by erikreedstrom** [comment]
Executing with deprecated `command` rather than `eval` does load the config, however any code that calls to Logger; i.e. DBConnection with migrations, causes a crash with `{'Elixir.Logger',level_to_number,[''],[{file,"lib/logger.ex"},{line,536}]}`.

**Comment by bitwalker** [comment]
This should be fixed in rc.10/master, can you confirm?

**Comment by erikreedstrom** [comment]
We cleaned and rebuilt from scratch, but issue still exists. On the plus side, no new issues.

**Comment by jung-hunsoo** [comment]
I'm having same problem. Unfortunately not solved in rc.10.

Since `var/sys.config` holds config values, I think envs aren't loaded in the pre_hook.

`IO.puts("#{Application.get_all_env(@app)}")` shows ` `.

**Comment by bitwalker** [comment]
I cannot reproduce this, with rc.10.

Given the following release definition:

```elixir
release :test do
  set version: current_version(:test)
  set pre_start_hooks: "rel/hooks/pre_start.d"
  set overlays: [
    {:copy, "config/config.exs", "etc/config.exs"}
  ]
  set config_providers: [
    {Mix.Releases.Config.Providers, ["${RELEASE_ROOT_DIR}/etc/config.exs"]}
  ]
end
```

A `config.exs` which looks like this:

```elixir
use Mix.Config

config :test,
  value: System.get_env("TEST_VAR")
```

And a pre_start hook in `rel/hooks/pre_start.d/test_hook.sh` like this:

```bash
#!/usr/bin/env bash

release_ctl eval "IO.inspect(Application.get_all_env(:test))"
```

I get the following when run:

```
$ TEST_VAR=foo _build/dev/rel/test/bin/test start
=INFO REPORT==== 12-Aug-2018::12:05:01.074859 ===
    application: mix
    exited: stopped
    type: temporary
[
  value: "foo"
]

$
```

The configuration is clearly available in the hook, and I have a similar test for custom commands.

Can either of you provide more information about your setup which may help me understand what is going wrong?

**Comment by erikreedstrom** [comment]
If we run without overlays, it runs the prestart hook and we get no config values.
If we run with overlays, it doesn't seem to run anything. It just exits.

**Comment by ybycode** [comment]
I created a repo with a fresh new elixir app and distillery master:

### Steps to reproduce

```sh
$ git clone git@github.com:ybycode/distillery2.0_test.git
$ cd distillery2.0_test.git
$ ./docker_run_bash.sh # optional, get a prompt in a container of a bitwalker/alpine-elixir image
$ mix do deps.get, compile
$ mix release
$ _build/dev/rel/myapp/bin/myapp eval "Application.get_all_env(:myapp) |> IO.inspect"
[]
```

**Comment by erikreedstrom** [comment]
Interesting @bitwalker... you are using `release_ctl` rather than the app bin 🤔

**Comment by erikreedstrom** [comment]
Tracing `"$RELEASES_DIR/$REL_VSN/libexec/erts.sh`, the call `ERTS_VSN="$(erts_vsn)"` is returning the following:

```
[
  mime: [
    types: %{
      "application/octet-stream" => ["xlsx"],
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" => ["xlsx"]
    }
  ],
  amqp: [
    queue: [rpc_queue: "core_api.rpc"],
    modules: [basic: AMQP.Basic, channel: AMQP.Channel, queue: AMQP.Queue]
  ],
  ecto: [json_library: Jason],
  # snip
  libcluster: [
    topologies: [
      k8s: [
        strategy: Cluster.Strategy.Kubernetes,
        config: [kubernetes_selector: nil, kubernetes_node_basename: nil]
      ]
    ]
  ]
]
=INFO REPORT==== 12-Aug-2018::20:37:52.587142 ===
    application: mix
    exited: stopped
    type: temporary
10.0.4
```
Pretty sure this is what's causing the script to bomb out.

**Comment by erikreedstrom** [comment]
It seems we are getting a full readout of the configs on every call to `eval`. Is there an `echo` hanging around somewhere from testing?

**Comment by jung-hunsoo** [comment]
@bitwalker Yes. Ground is OTP 21 + Elixir 1.7.0 + rc.11.

`rel/config.exs`:
```elixir
release :nohogu do
  set version: current_version(:nohogu)
  set applications: [
    :runtime_tools
  ]
  set overlays: [
    {:copy, "config/config.exs", "etc/config.exs"}
  ]
  set config_providers: [
    {Mix.Releases.Config.Providers, ["${RELEASE_ROOT_DIR}/etc/config.exs"]}
  ]
  set pre_start_hooks: "rel/hooks/pre_start.d"
end
```

Error message is;
```
function Mix.Releases.Config.Providers.init/1 is undefined (module Mix.Releases.Config.Providers is not available)
    Mix.Releases.Config.Providers.init(["${RELEASE_ROOT_DIR}/etc/config.exs"])
    (distillery) lib/mix/lib/releases/config/provider.ex:97: anonymous fn/2 in Mix.Releases.Config.Provider.init/1
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (distillery) lib/mix/lib/releases/config/provider.ex:88: Mix.Releases.Config.Provider.init/1
    :init.eval_script/2
    :init.do_boot/3

{"init terminating in do_boot",{#{'__exception__'=>true,'__struct__'=>'Elixir.UndefinedFunctionError',arity=>1,function=>init,message=>nil,module=>'Elixir.Mix.Releases.Config.Providers',reason=>nil},[{'Elixir.Mix.Releases.Config.Providers',init,[[<<"${RELEASE_ROOT_DIR}/etc/config.exs">>]],[]},{'Elixir.Mix.Releases.Config.Provider','-init/1-fun-0-',2,[{file,"lib/mix/lib/releases/config/provider.ex"},{line,97}]},{'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,[{file,"lib/enum.ex"},{line,1925}]},{'Elixir.Mix.Releases.Config.Provider',init,1,[{file,"lib/mix/lib/releases/config/provider.ex"},{line,88}]},{init,eval_script,2,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({,[{Elixir.Mix.Releases.Config.Providers,init,[[_]],[]},{Elixir.Mix.Releases.Config.Provider,-init/1-fun-0-,2,[{_},{_}]},{Elixir.Enum,-reduce/3-lists^foldl/2-0-,3,[{_},{_}

Crash dump is being written to: erl_crash.dump...done
```

**Comment by AlexKovalevych** [comment]
May be related (using rc11), elixir:1.6.6-alpine docker image:

error:

```
init terminating in do_boot ({,[{Elixir.File,read!,1,[{_},{_}]},{Elixir.Toml.Decoder,decode_file!,2,[{_},{_}]},{Elixir.Toml.Provider,init,1,[{_},{_}]},{Elixir.Mix.Releases.Config.Provider,-init/1-fun-
```

Release providers config:

```
  set(
    config_providers: [
      {Toml.Provider, [path: "/app/config.toml"]}
    ]
  )
```

**Comment by bitwalker** [comment]
@AlexKovalevych In your case, it can't find the file (it's raising an error during `File.read!/1`)

@jung-hunsoo Can you show the `environment` definition that the release is built with, and the contents of the `pre_start.d` hooks?

**Comment by jung-hunsoo** [comment]
@bitwalker My build env is on docker too. Docker (windows 10) + Ubuntu 18.04 + OTP 21 + Elixir 1.7.0.

The `env` is one of Phoenix 1.3.3 generation.

`config/config.exs`
```elixir
# This file is responsible for configuring your application
# and its dependencies with the aid of the Mix.Config module.
#
# This configuration file is loaded before any dependency and
# is restricted to this project.
use Mix.Config

# General application configuration
config :nohogu,
  ecto_repos: [Nohogu.Repo],
	env: Mix.env

# Configures the endpoint
config :nohogu, NohoguWeb.Endpoint,
  url: [host: "localhost"],
  secret_key_base: SCREENED,
  render_errors: [view: NohoguWeb.ErrorView, accepts: ~w(html json)],
  pubsub: [name: Nohogu.PubSub,
           adapter: Phoenix.PubSub.PG2]

# Configures Elixir's Logger
config :logger, :console,
  format: "$time $metadata[$level] $message\n",
  metadata: [:user_id]

config :gettext, default_locale: "ko"
config :gettext, NohoguWeb.Gettext, default_locale: "ko"

config :ex_cldr,
	locales: ~w(en en-001 ko),
	gettext: NohoguWeb.Gettext,
	precompile_number_formats: ["¤¤#,##0.##"]

# Drab
config :phoenix, :template_engines,
  drab: Drab.Live.Engine

config :drab, NohoguWeb.Endpoint,
  otp_app: :nohogu

# %% Coherence Configuration %%   Don't remove this line
config :coherence,
  ...SCREENED...
# %% End Coherence Configuration %%

config :coherence_assent, :providers,
	[
		twitter: [
			strategy: CoherenceAssent.Strategy.Twitter
		],
		facebook: [
			strategy: CoherenceAssent.Strategy.Facebook
		]
# 		github: [
# 			client_id: "REPLACE_WITH_CLIENT_ID",
# 			client_secret: "REPLACE_WITH_CLIENT_SECRET",
# 			strategy: CoherenceAssent.Strategy.Github
# 		]
	]

# AWS settings
config :ex_aws,
  region: "ap-northeast-2",
  s3: [
    scheme: "https://",
    host: "s3-ap-northeast-2.amazonaws.com",
    region: "ap-northeast-2"
  ]

config :arc,
  storage: Arc.Storage.S3,
  virtual_host: true

config :kerosene,
	theme: :semantic

import_config "#{Mix.env}.exs"
```

I tried both way; 1) Copy `config/` to `etc/` via overlay then start build, 2) Merge `config/config.exs` and `config/prod.exs` then copy `config/prod.exs` to `etc/prod.exs` via overlay and start build.

And here's `pre_start.d/pre_start.sh`:
```
#!/bin/bash
${RELEASE_ROOT_DIR}/bin/nohogu eval "Nohogu.Tasks.ReleaseTasks.setup()"
```

**Comment by bitwalker** [comment]
@jung-hunsoo What about if you replace `${RELEASE_ROOT_DIR/bin/nohogu` with `release_ctl` in your hook?

**Comment by jung-hunsoo** [comment]
@bitwalker Still have the same error.
```

function Mix.Releases.Config.Providers.init/1 is undefined (module Mix.Releases.Config.Providers is not available)
    Mix.Releases.Config.Providers.init(["${RELEASE_ROOT_DIR}/etc/config.exs"])
    (distillery) lib/mix/lib/releases/config/provider.ex:97: anonymous fn/2 in Mix.Releases.Config.Provider.init/1
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (distillery) lib/mix/lib/releases/config/provider.ex:88: Mix.Releases.Config.Provider.init/1
    :init.eval_script/2
    :init.do_boot/3

{"init terminating in do_boot",{#{'__exception__'=>true,'__struct__'=>'Elixir.UndefinedFunctionError',arity=>1,function=>init,message=>nil,module=>'Elixir.Mix.Releases.Config.Providers',reason=>nil},[{'Elixir.Mix.Releases.Config.Providers',init,[[<<"${RELEASE_ROOT_DIR}/etc/config.exs">>]],[]},{'Elixir.Mix.Releases.Config.Provider','-init/1-fun-0-',2,[{file,"lib/mix/lib/releases/config/provider.ex"},{line,97}]},{'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,[{file,"lib/enum.ex"},{line,1925}]},{'Elixir.Mix.Releases.Config.Provider',init,1,[{file,"lib/mix/lib/releases/config/provider.ex"},{line,88}]},{init,eval_script,2,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({,[{Elixir.Mix.Releases.Config.Providers,init,[[_]],[]},{Elixir.Mix.Releases.Config.Provider,-init/1-fun-0-,2,[{_},{_}]},{Elixir.Enum,-reduce/3-lists^foldl/2-0-,3,[{_},{_}

Crash dump is being written to: erl_crash.dump...done
```

**Comment by bitwalker** [comment]
@jung-hunsoo Can you gist the output of running the release with `DEBUG_BOOT=true` exported? I'm going to have to try and see what is going on in your environment that way. Could you also update to the latest on master?

**Comment by jung-hunsoo** [comment]
@bitwalker Wow this is great. I'll dig more in this crash dump.

Command was `REPLACE_OS_VARS=true PORT=4000 DEBUG_BOOT=true bin/nohogu foreground`.

https://gist.github.com/jung-hunsoo/f30c83cb776cb602b01bd4930efa8883

**Comment by bitwalker** [comment]
@jung-hunsoo You haven't updated to the latest on master, the debug output shows that lines it has to be hitting (i.e. they come right after lines I _do_ see in the output) which were added in the latest changes, aren't being hit. Can you confirm the sha hash in `mix.lock` for the Distillery dependency?

**Comment by jung-hunsoo** [comment]
@bitwalker Crash dump says `(module Mix.Releases.Config.Providers is not available)`.

In the `/lib/distillery-2.0.0-rc.11/ebin/`, there're two similar modules; `Elixir.Mix.Releases.Config.Provider.beam` and `Elixir.Mix.Releases.Config.Providers.Elixir.beam`.

But, is it necessary to use option of `config_provider`? And what if there're two partial config files are exists? Since that's the default in phoenix; `config.exs`, `dev.exs`, `dev.secret.exs`, `prod.exs`, and `test.exs`. Should the phx users transform the config files, or just copy the directory using `{:copy, "config/", "etc/"}` overlay is enough? I belive simple is better if there's a de facto way.

**Comment by jung-hunsoo** [comment]
@bitwalker If I remove `overlay` and `config_providers` in the `rel/config.exs`, no mix envs are loaded. When I use `overlay` and `config_providers` as described above, same error.

Hash is `b797361a95880d5aec180e86259ad6f520fa7b71ffd27673a99332313bbae274`.

**Comment by bitwalker** [comment]
@jung-hunsoo Can you update Distillery (`mix deps.update distillery`), rebuild your release, and try again?

**Comment by jung-hunsoo** [comment]
@bitwalker I changed the `config_providers` in `rel/config.exs` from `{Mix.Releases.Config.Providers, ["${RELEASE_ROOT_DIR}/etc/config.exs"]}` to `{Mix.Releases.Config.Providers.Elixir, ["${RELEASE_ROOT_DIR}/etc/config.exs"]}`. Now the `not found` error is solved.

And FINALLY the env is carried. But the values aren't replaced which means;
`[{:env, :prod}, {:ecto_repos, [Nohogu.Repo]}, {Nohogu.Repo, [adapter: Ecto.Adapters.Postgres, username: "${DB_USERNAME}", password: "${DB_PASSWORD}", database: "${DB_NAME}", hostname: "${DB_HOSTNAME}", pool_size: 20]}, {NohoguWeb.Endpoint, [render_errors: [view: NohoguWeb.ErrorView, accepts: ["html", "json"]], pubsub: [name: Nohogu.PubSub, adapter: Phoenix.PubSub.PG2], http: [port: "${PORT}"], url: [host: "${HOST}", port: "${PORT}"], cache_static_manifest: "priv/static/cache_manifest.json", secret_key_base: "${SECRET_KEY_BASE}", server: true, root: ".", version: '0.0.1']}]`

The `REPLACE_OS_VARS=true` didn't worked.

**Comment by bitwalker** [comment]
The env var replacement is only for sys.config and vm.args, use the standard library Elixir functions in your config.exs to handle them with the Elixir provider.

Why did you use `Mix.Releases.Config.Providers` originally? Did you find that in the docs somewhere? Sorry I didn't notice that before

**Comment by jung-hunsoo** [comment]
@bitwalker As a solution, I configured db env vars in `Repo.init/2`. It was done in `config/prod.exs`, but can't connect to db, so I changed to use `Repo.init/2` instead. Not so bad, except it won't be reloaded when hot upgrading.

`Mix.Releases.Config.Providers` were from your last Saturday night's comment. OMG you had a Saturday night at github.

Anyway now I can successfully migrate my DB through the `pre_start.sh` hook. Your help was so much appreciated.
