### ISSUE TITLE
Error on mix.exs deps check

### ISSUE THREAD

**Issue by schurig** [bitwalker/distillery#50]
### Steps to reproduce

`mix release`

### Verbose Logs

```
** (CaseClauseError) no case clause matching: nil
    lib/mix/lib/releases/models/app.ex:92: Mix.Releases.App.include_dep?/1
    (elixir) lib/enum.ex:807: anonymous fn/4 in Enum.filter_map/3
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:807: Enum.filter_map/3
    lib/mix/lib/releases/models/app.ex:42: Mix.Releases.App.new/2
    lib/mix/lib/releases/utils.ex:198: Mix.Releases.Utils.get_apps/1
    lib/mix/lib/releases/assembler.ex:78: Mix.Releases.Assembler.apply_configuration/2
    lib/mix/lib/releases/assembler.ex:27: Mix.Releases.Assembler.assemble/1
    lib/distillery/tasks/release.ex:106: Mix.Tasks.Release.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

### Description of issue

This error is present since the 0.9.3 version. It might be because of [e40fe54](https://github.com/bitwalker/distillery/commit/e40fe54be66b72927b393593649bd5d11dd19606)

my mix.exs looks like this:

```elixir
defmodule MyApp.Mixfile do
  use Mix.Project

  def project do
    [app: :my_app,
     version: version_number(),
     elixir: "~> 1.3.0",
     elixirc_paths: elixirc_paths(Mix.env),
     compilers: [:phoenix, :gettext] ++ Mix.compilers,
     build_embedded: Mix.env == :prod || Mix.env == :beta,
     start_permanent: Mix.env == :prod || Mix.env == :beta,
     aliases: aliases(),
     consolidate_protocols: false,
     test_coverage: [tool: ExCoveralls],
     preferred_cli_env: ["coveralls": :test, "coveralls.detail": :test, "coveralls.html": :test],
     deps: deps() ++ dev_test_deps()]
  end

  # Configuration for the OTP application.
  #
  # Type `mix help compile.app` for more information.
  def application do
    [mod: {MyApp, []},
     applications: Enum.map(deps(), fn({package, _version}) -> package end) ++ [:logger, :runtime_tools, :mix]]
  end

  # Specifies which paths to compile per environment.
  defp elixirc_paths(:test), do: ["lib", "web", "test/support"]
  defp elixirc_paths(_),     do: ["lib", "web"]

  # Specifies your project dependencies.
  #
  # Type `mix help deps` for examples and options.
  defp deps do
    [
      {:arc_ecto, "~> 0.4.3"},
      {:arc, "~> 0.5.2"},
      {:bamboo_smtp, "~> 1.2.0"},
      {:bamboo, "~> 0.7"},
      {:calecto, "~> 0.16.0"},
      {:calendar_translations, "~> 0.0.3"},
      {:calendar, "~> 0.16.0"},
      {:comeonin, "~> 2.5"},
      {:cowboy, "~> 1.0"},
      {:credo, "~> 0.4.5"},
      {:earmark, "~> 1.0.0"},
      {:ecto, "~> 2.0.1"},
      {:edeliver, "~> 1.4.0"},
      {:eiconv, git: "https://github.com/zotonic/eiconv.git"},
      {:ex_aws, "~> 0.5.0"},
      {:geo, "~> 1.1"},
      {:gettext, "~> 0.11"},
      {:html_sanitize_ex, "~> 1.0.1"},
      {:httpoison, "~> 0.9.0"},
      {:icalendar, git: "https://github.com/lpil/icalendar.git"},
      {:joken, "~> 1.2.2"},
      {:mailman, "~> 0.2.2"},
      {:oauth2, "0.6.0"},
      {:phoenix_calendar, "~> 0.1.2"},
      {:phoenix_ecto, "~> 3.0.0"},
      {:phoenix_html, ">= 2.6.2"},
      {:phoenix_pubsub, "~> 1.0"},
      {:phoenix_simple_form, ">= 0.0.0"},
      {:phoenix, "~> 1.2.1"},
      {:porcelain, "~> 2.0"},
      {:postgrex, ">= 0.0.0"},
      {:quantum, ">= 1.7.1"},
      {:scrivener_ecto, "~> 1.0"},
      {:scrivener_html, "~> 1.3.1"},
      {:scrivener, "~> 2.0.0"}
      # {:exrm, "~> 1.0"},
    ]
  end

  defp dev_test_deps do
    [
      {:distillery, ">= 0.9.0", warn_missing: false},
      {:ex_machina, "~> 1.0", only: :test},
      {:excoveralls, "~> 0.4", only: :test},
      {:mix_test_watch, "~> 0.2", only: :dev},
      {:phoenix_live_reload, "~> 1.0", only: :dev},
      {:sshex, "2.1.0", only: [:dev, :test]}
    ]
  end

  # See the documentation for `Mix` for more info on aliases.
  defp aliases do
    ["ecto.setup": ["ecto.create", "ecto.load", "ecto.migrate", "run priv/repo/seeds.exs"],
     "ecto.reset": ["ecto.drop", "ecto.setup"],
     "phoenix.server": ["ecto.migrate", "phoenix.server"],
     "s": ["phoenix.server"],
     "t": ["test.watch"],
     "c": ["clean", "deps.clean --all", "deps.get", "compile"],
     "credo": ["credo --strict"],
     "project-version": ["run -e 'IO.puts MyApp.Mixfile.project[:version]'"],
     "test": ["ecto.create --quiet", "ecto.migrate", "test"]]
  end

  defp version_number do
    {output, 0} = System.cmd("git", ["rev-list", "--count", "HEAD"])
    "1.0." <> String.rstrip(output)
  end
end
```

**Comment by AndrewDryga** [comment]
+1

**Comment by bitwalker** [comment]
This is already fixed in master. I'll get it pushed to hex.

**Comment by schurig** [comment]
Still getting an error with 0.9.4 :(
(but an other one this time)

```
** (Protocol.UndefinedError) protocol Enumerable not implemented for :test
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:131: Enumerable.member?/2
    (elixir) lib/enum.ex:1352: Enum.member?/2
    (elixir) lib/enum.ex:807: anonymous fn/4 in Enum.filter_map/3
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:807: Enum.filter_map/3
    lib/mix/lib/releases/models/app.ex:42: Mix.Releases.App.new/2
    lib/mix/lib/releases/utils.ex:198: Mix.Releases.Utils.get_apps/1
```

**Comment by bitwalker** [comment]
Ah it's because of `only: :test`, the code is expecting a list there not a single atom, I'll get that fixed.

**Comment by bitwalker** [comment]
Try 0.9.5 :)

**Comment by schurig** [comment]
@bitwalker I'm afraid there is still something wrong :/

```
** (ArgumentError) argument error
    (stdlib) :lists.member(:ex_doc, [:distillery | nil])
    (elixir) lib/enum.ex:1348: Enum.member?/2
    lib/mix/lib/releases/utils.ex:231: anonymous fn/2 in Mix.Releases.Utils.get_apps/1
    (elixir) lib/enum.ex:787: anonymous fn/3 in Enum.filter/2
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:787: Enum.filter/2
    lib/mix/lib/releases/utils.ex:230: Mix.Releases.Utils.get_apps/1
    lib/mix/lib/releases/assembler.ex:78: Mix.Releases.Assembler.apply_configuration/2
```

**Comment by bitwalker** [comment]
Pushed 0.9.6...sigh

**Comment by schurig** [comment]
Works!!! Thank you :) 👍

**Comment by bitwalker** [comment]
Awesome :)
